=== raml-apis/Squareup/schemas/itemReq-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "string" ,
      "required" : false
    } ,
    "category_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "variations" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "pricing_type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "price_money" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "currency_code" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "amount" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "sku" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Squareup/examples/item-example.json
{
  "name" : "Milkshake" ,
  "description" : "It's better than yours" ,
  "visibility" : "PRIVATE" ,
  "category_id" : "36ac7016-3a4e-4934-81f1-9057ac613f2y" ,
  "variations" : [
    {
      "name" : "Small" ,
      "pricing_type" : "FIXED_PRICING" ,
      "price_money" : {
        "currency_code" : "USD" ,
        "amount" : 400
      } ,
      "sku" : "123"
    }
  ]
}
