=== raml-apis/Squareup/schemas/itemVariation-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "pricing_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "track_inventory" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "inventory_alert_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "price_money" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "currency_code" : {
          "type" : "string" ,
          "required" : false
        } ,
        "amount" : {
          "type" : "number" ,
          "required" : false
        }
      }
    } ,
    "ordinal" : {
      "type" : "number" ,
      "required" : false
    } ,
    "item_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "inventory_alert_threshold" : {
      "type" : "number" ,
      "required" : false
    } ,
    "user_data" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Squareup/examples/itemVariation-example.json
{
  "pricing_type" : "FIXED_PRICING" ,
  "track_inventory" : true ,
  "inventory_alert_type" : "LOW_QUANTITY" ,
  "id" : "cb890728-cfdc-4690-9e03-349f964f756r" ,
  "name" : "Small" ,
  "price_money" : {
    "currency_code" : "USD" ,
    "amount" : 400
  } ,
  "ordinal" : 0 ,
  "item_id" : "442d1344-6d2b-4238-83d0-0284dfd335d8" ,
  "inventory_alert_threshold" : 10 ,
  "user_data" : "SEASONAL=TRUE"
}
