=== raml-apis/Squareup/schemas/item-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "string" ,
      "required" : false
    } ,
    "available_online" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "category_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "category" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "variations" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "pricing_type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "price_money" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "currency_code" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "amount" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "ordinal" : {
              "type" : "number" ,
              "required" : false
            } ,
            "item_id" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Squareup/examples/items-example.json
[
  {
    "id" : "442d1344-6d2b-4238-83d0-0284dfd335d8" ,
    "name" : "Milkshake" ,
    "description" : "It's better than yours" ,
    "visibility" : "PRIVATE" ,
    "available_online" : false ,
    "category" : {
      "id" : "36ac7016-3a4e-4934-81f1-9057ac613f2y" ,
      "name" : "Beverages"
    } ,
    "variations" : [
      {
        "id" : "cb890728-cfdc-4690-9e03-349f964f756r" ,
        "name" : "Small" ,
        "pricing_type" : "FIXED_PRICING" ,
        "price_money" : {
          "currency_code" : "USD" ,
          "amount" : 400
        } ,
        "ordinal" : 0 ,
        "item_id" : "442d1344-6d2b-4238-83d0-0284dfd335d8"
      } ,
      "..."
    ]
  } , {
    "id" : "442d1344-6d2b-4238-83d0-0284dfd335d8" ,
    "name" : "Milkshake" ,
    "description" : "It's better than yours" ,
    "visibility" : "PRIVATE" ,
    "available_online" : false ,
    "category" : {
      "id" : "36ac7016-3a4e-4934-81f1-9057ac613f2y" ,
      "name" : "Beverages"
    } ,
    "variations" : [
      {
        "id" : "cb890728-cfdc-4690-9e03-349f964f756r" ,
        "name" : "Small" ,
        "pricing_type" : "FIXED_PRICING" ,
        "price_money" : {
          "currency_code" : "USD" ,
          "amount" : 400
        } ,
        "ordinal" : 0 ,
        "item_id" : "442d1344-6d2b-4238-83d0-0284dfd335d8"
      } ,
      "..."
    ]
  }
]
