=== raml-apis/Squareup/schemas/merchant-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "email" : {
      "type" : "string" ,
      "required" : false
    } ,
    "country_code" : {
      "type" : "string" ,
      "required" : false
    } ,
    "language_code" : {
      "type" : "string" ,
      "required" : false
    } ,
    "business_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "business_address" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "address_line_1" : {
          "type" : "string" ,
          "required" : false
        } ,
        "locality" : {
          "type" : "string" ,
          "required" : false
        } ,
        "administrative_district_level_1" : {
          "type" : "string" ,
          "required" : false
        } ,
        "postal_code" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "business_phone" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "calling_code" : {
          "type" : "string" ,
          "required" : false
        } ,
        "number" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "business_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "account_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "location_details" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "nickname" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "market_url" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Squareup/examples/merchant-example.json
{
  "id" : "JGHJ0343" ,
  "name" : "Dave Davis" ,
  "email" : "dave@example.com" ,
  "country_code" : "US" ,
  "language_code" : "en-US" ,
  "business_name" : "Dave's Milkshakes" ,
  "business_address" : {
    "address_line_1" : "1455 Market St" ,
    "locality" : "San Francisco" ,
    "administrative_district_level_1" : "CA" ,
    "postal_code" : "94103"
  } ,
  "business_phone" : {
    "calling_code" : "+1" ,
    "number" : "4155551234"
  } ,
  "business_type" : "restaurants" ,
  "account_type" : "LOCATION" ,
  "location_details" : {
    "nickname" : "Milkshakes"
  } ,
  "market_url" : "https://mkt.com/squared"
}
