=== raml-apis/Squareup/schemas/page-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "page_index" : {
      "type" : "number" ,
      "required" : false
    } ,
    "cells" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
      ]
    }
  }
}

=== raml-apis/Squareup/examples/pages-example.json
[
  {
    "id" : "c87595ae-14a6-42d7-acb6-008fc8e7ed3g" ,
    "name" : "Lunch Items" ,
    "page_index" : 0 ,
    "cells" : [
      {
        "page_id" : "343F7510-7214-4EB2-9B93-9DA3903327EB" ,
        "row" : 0 ,
        "column" : 0 ,
        "object_type" : "ITEM" ,
        "object_id" : "442d1344-6d2b-4238-83d0-0284dfd335d8"
      }
    ]
  } , {
    "id" : "c87595ae-14a6-42d7-acb6-008fc8e7ed3g" ,
    "name" : "Lunch Items" ,
    "page_index" : 0 ,
    "cells" : [
      {
        "page_id" : "343F7510-7214-4EB2-9B93-9DA3903327EB" ,
        "row" : 0 ,
        "column" : 0 ,
        "object_type" : "ITEM" ,
        "object_id" : "442d1344-6d2b-4238-83d0-0284dfd335d8"
      }
    ]
  }
]
