=== raml-apis/Squareup/schemas/settlement-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "bank_account_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "initiated_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "total_money" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "amount" : {
          "type" : "number" ,
          "required" : false
        } ,
        "currency_code" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "entries" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "payment_id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "amount_money" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "amount" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "currency_code" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "fee_money" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "amount" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "currency_code" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Squareup/examples/settlements-example.json
[
  {
    "id" : "C:34GEWHCJGPR40" ,
    "status" : "SENT" ,
    "bank_account_id" : "JGHJ0343" ,
    "initiated_at" : "2013-01-02T08:00:00.000Z" ,
    "total_money" : {
      "amount" : 5981 ,
      "currency_code" : "USD"
    }
  } , {
    "id" : "C:34GEWHCJGPR40" ,
    "status" : "SENT" ,
    "bank_account_id" : "JGHJ0343" ,
    "initiated_at" : "2013-01-02T08:00:00.000Z" ,
    "total_money" : {
      "amount" : 5981 ,
      "currency_code" : "USD"
    }
  }
]

=== raml-apis/Squareup/examples/settlement-example.json
{
  "id" : "C:34GEWHCJGPR40" ,
  "status" : "SENT" ,
  "bank_account_id" : "543654645" ,
  "initiated_at" : "2013-01-02T08:00:00.000Z" ,
  "total_money" : {
    "amount" : 5981 ,
    "currency_code" : "USD"
  } ,
  "entries" : [
    {
      "payment_id" : "Jq74mCczmFXk1tC10GB" ,
      "type" : "CHARGE" ,
      "amount_money" : {
        "amount" : 5981 ,
        "currency_code" : "USD"
      } ,
      "fee_money" : {
        "amount" : -169 ,
        "currency_code" : "USD"
      }
    } , {
      "payment_id" : "Jq74mCczmFXk1tC10GB" ,
      "type" : "CHARGE" ,
      "amount_money" : {
        "amount" : 5981 ,
        "currency_code" : "USD"
      } ,
      "fee_money" : {
        "amount" : -169 ,
        "currency_code" : "USD"
      }
    }
  ]
}
